### ISSUE TITLE
assert connection does not seem to function properly

### ISSUE THREAD

**Issue by hassenius** [locke105/pylogmet#3]
When there is 2 minutes or more between each emitter event, the connection seems to time out that should have been handled by _assert_connection
Example
Emitting metrics
Sleeping for 60 seconds
Emitting metrics
Sleeping for 90 seconds
Emitting metrics
Sleeping for 120 seconds
Emitting metrics
No handlers could be found for logger "logmet"
Traceback (most recent call last):
  File "testclient.py", line 28, in <module>
    lm.emit_metric(name='logmet.test.1', value=1)
  File "pylogmet/logmet/__init__.py", line 122, in emit_metric
    self._send_metric(metric_msg)
  File "pylogmet/logmet/__init__.py", line 158, in _send_metric
    self.socket.sendall(metrics_package)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

**Comment by mrodden** [comment]
I wonder if Logmet changed something on their end, because it looks like its not sending the FIN packet which leaves a few bytes on the incoming socket queue that the select() is supposed to pick up and rebuild the connection if it sees.

I will look into this more, and probably add a backup "just try it and get a new connection if it fails" type of reconnect as well.

**Comment by mrodden** [comment]
@hassenius can you try commit 18b40fbba (the latest on master) and see if that fixes the issue you are seeing?

**Comment by hassenius** [comment]
Yup, not getting any timeouts after this
Cheers!
